service: import-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::julia-ivv-stall-import"
    - Effect: "Allow"
      Action: "s3:*"
      Resource:
        - "arn:aws:s3:::julia-ivv-stall-import/*"
  
functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: julia-ivv-stall-import
          rules: 
            - prefix: uploaded/
          existing: true